Cli2restart -- See if this is close
decko-commons/decko pull request #544
Opened 2020-10-08 11:33 UTC by GerryG

Was loading and running tests, but my local DB was messing up.

2020-10-09 14:27 UTC, GerryG commented
Oh, maybe it is the updates I didn't merge yet.

2020-10-09 14:34 UTC, GerryG commented
NVM, got it to fail ... it isn't loading right for shark decks.

2020-10-10 22:27 UTC, ethn requested changes

2020-10-10 22:27 UTC, ethn commented on card/lib/card/config/environments/cucumber.rb
> +end
If something is breaking when these aren't here, that's a bug.

2020-10-10 22:27 UTC, ethn commented on card/lib/card/env/location.rb
> -          "#{Card.config.relative_url_root}/#{rel_path}"
if you've already loaded Card, then Card.config is still an acceptable alternative to Cardio.config, right?  And if you're in a subclass of Card, you've already loaded Card, right?

2020-10-10 22:27 UTC, ethn commented on card/lib/card/essential.rb
> +require 'card/director'
this is also bad. please remove.

2020-10-10 22:27 UTC, ethn commented on card/lib/card/name/fields_and_traits.rb
> +  class Name < Cardname
not necessary, please remove.

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio.rb
> +  module RailsConfigMethods
modules like this should be in cardio subdir.  (eg cardio/rails_config_methods.rb). Those will need to be explicitly required.

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio/commands.rb
> +  module Commands
These changes leave a TON of duplicate code in decko and card.  Anything that's already in cardio should be includable in decko.

2020-10-10 22:27 UTC, ethn commented on card/spec/spec_helper.rb
> +require "decko/commands/application"
should not be necessary here.

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio/application.rb
> +require 'rails'
too general. Even decko doesn't require "rails"

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio/application_record.rb
> +ActiveSupport.run_load_hooks(:after_application_record, self)
I think I would just leave this stuff out for now.  out of scope.

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio/commands/rake_command/parser.rb
> +                          "Run card:#{command} task on the production "\
does this mean monkeys will be seeing help text for the `card` command? We may need to override this in decko.

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio/config/initializers/secret_token.rb
> +end
can't have this in repo.

2020-10-10 22:27 UTC, ethn commented on card/lib/cardio/mod_inflector.rb
> +class ModInflector < Zeitwerk::Inflector
shouldn't this be a `git mv` of old file?

2020-10-10 22:27 UTC, ethn commented on decko/lib/decko/config/environments/cucumber.rb
> +Decko::Application.configure do
This is wrong. 

When you make a deck, eg wikirate, it generates a new application class, eg WikirateApplication, which inherits from Decko::Application.  Decko.application.class returns WikirateApplication.

2020-10-10 22:27 UTC, ethn commented on decko/lib/decko/config/environments/test.rb
> +Decko::Application.configure do
This might be what's breaking your specs.

2020-10-10 22:55 UTC, ethn commented on card-mod-defaults/card-mod-defaults.gemspec
> +    :carrierwave, :bootstrap, :account, :history, :delayed_job
old version is correct, according to our current rubocop config.

2020-10-10 22:56 UTC, ethn commented on card/lib/card/env/location.rb
> -          "#{Card.config.relative_url_root}/#{rel_path}"
I think Card.config will probably be the more approachable convention when already inside card context.

2020-10-12 13:54 UTC, ethn commented on card-mod-delayed_job/config/initializers/delayed_job_config.rb
> +return unless Card.config.active_job.queue_adapter == :delayed_job
here it has to be Cardio.  Card is not loaded yet.

2020-10-12 13:54 UTC, ethn commented on card-mod-delayed_job/config/initializers/delayed_job_config.rb
> +return unless Card.config.active_job.queue_adapter == :delayed_job
oh, maybe it is for now. Sorry.  I want this to be loaded earlier but that's not an option yet...

2020-10-12 13:55 UTC, ethn commented on card-mod-monkey/lib/card/pry.rb
> +class Card
This is wrong.  Card is not loaded yet.

2020-10-12 13:58 UTC, ethn commented on card/lib/card/config/environments/cucumber.rb
> +Cardio.application.class.configure do
There is no whitelist of environments.  We must get rid of these files.

2020-10-12 13:58 UTC, ethn commented on card/lib/card/config/initializers/secret_token.rb
> +end
this can't be here!!

2020-10-14 11:27 UTC, closed without merging